export { ReactComponent as LogoIcon } from "./logoIcon.svg";
export { ReactComponent as ListSelectedIcon } from "./List_selected_16.svg";
export { ReactComponent as ListUnSelectedIcon } from "./List_unselected_16.svg";
export { ReactComponent as ArrowDownIcon } from "./Arrow_down.svg";
export { ReactComponent as ArrowSideIcon } from "./Arrow_side.svg";
export { ReactComponent as FolderIcon } from "./Folder.svg";
export { ReactComponent as Search24Icon } from "./Icons_Search_24.svg";
export { ReactComponent as SelectedTrashIcon } from "./Icons_trash_selected.svg";
export { ReactComponent as UnselectedTrashIcon } from "./Icons_trash_unselected.svg";
